[workspace]
members = ["ml_processor"]

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
apriori = { git = "https://github.com/SichangHe/remykarem--apriori" }
bincode = "1.3"
log = "0.4"
