apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs401-sh623-hw3-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs401-sh623-hw3-runtime
  template:
    metadata:
      labels:
        app: cs401-sh623-hw3-runtime
    spec:
      containers:
      - name: cs401-sh623-hw3-runtime
        image: lucasmsp/serverless:redis # TODO: Switch
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "10.244.0.1"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
