apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs401-sh623-hw3-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs401-sh623-hw3-runtime
  template:
    metadata:
      labels:
        app: cs401-sh623-hw3-runtime
    spec:
      containers:
      - name: cs401-sh623-hw3-runtime
        image: sssstevenhe/cs401-hw3-runtime:0.2.0
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        - name: zipped-module
          mountPath: "/opt/function_module.zip"
        env:
        - name: REDIS_HOST
          value: "10.244.0.1"
        - name: REDIS_PORT
          value: "6379"
        # Optional ConfigMap: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#optional-configmaps>
        - name: REDIS_INPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: REDIS_INPUT_KEY
              optional: true
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: POLL_INTERVAL_SECONDS
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: POLL_INTERVAL_SECONDS
              optional: true
        - name: ZIPPED_MODULE_NAME
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: ZIPPED_MODULE_NAME
              optional: true
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
          optional: true
      - name: zipped-module
        configMap:
          name: zipped-module
          # optional: true
