apiVersion: v1
kind: Pod
metadata:
  name: runtime-dbg-pod
spec:
  containers:
  - name: runtime-dbg
    image: python:3.12.2-slim
    volumeMounts:
    - name: pyfile
      mountPath: "/opt/usermodule.py"
      subPath: pyfile
    - name: zipped-module
      mountPath: "/opt/function_module.zip"
    env:
  volumes:
  - name: pyfile
    configMap:
      name: pyfile
      optional: true
  - name: zipped-module
    configMap:
      name: zipped-module
      optional: true
