apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs401-sh623-hw3-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs401-sh623-hw3-runtime
  template:
    metadata:
      labels:
        app: cs401-sh623-hw3-runtime
    spec:
      containers:
      - name: cs401-sh623-hw3-runtime
        image: sssstevenhe/cs401-hw3-runtime:0.3.0
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        - name: module-zip
          mountPath: "/opt/function_module/"
        env:
        - name: REDIS_HOST
          value: "10.244.0.1"
        - name: REDIS_PORT
          value: "6379"
        # Optional ConfigMap: <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#optional-configmaps>
        - name: REDIS_INPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: REDIS_INPUT_KEY
              optional: true
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: POLL_INTERVAL_SECONDS
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: POLL_INTERVAL_SECONDS
              optional: true
        - name: FUNCTION_ZIP_PATH
          value: "/opt/function_module/function_module.zip"
        - name: ZIPPED_MODULE_NAME
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: ZIPPED_MODULE_NAME
              optional: true
        - name: HANDLER_FUNCTION_NAME
          valueFrom:
            configMapKeyRef:
              name: runtime-improved
              key: HANDLER_FUNCTION_NAME
              optional: true
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
          optional: true
      - name: module-zip
        configMap:
          name: runtime-improved
          # <https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-specific-path-in-the-volume>
          items:
            - key: zipped-module
              path: function_module.zip
          optional: true
